name: E2E-TESTS

on:
  pull_request:
    branches:
      - production

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      # - name: Install dependencies
      #   run: npm install
      # - name: Install playwright browsers
      #   run: npx playwright install --with-deps
      # - name: Run tests
      #   run: npx playwright test
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: ./client/playwright-report/
      #     retention-days: 30
